### ISSUE TITLE
faq regarding HLSL and vulkan is not up to date?

### ISSUE THREAD

**Issue by alek314** [KhronosGroup/Khronosdotorg#64]
The following source says there is "HLSL support" in vulkan 1.1 core. 
[https://www.khronos.org/assets/uploads/developers/library/overview/Vulkan-1-1-Presentation_Mar18.pdf](url)
Can you clarify this remark on the Khronosdotorg/api/vulkan/faq.md page?
e.g: Is there a new version of HLSL which support "binding", "set" key word?
Thank you.

**Comment by TomOlson** [comment]
The presentation is talking about the VK_KHR_relaxed_block_layout extension, which was promoted to core in Vulkan 1.1. It loosens some Valid Usage constraints in Chapter 14, so that it becomes possible to support all of the cbuffer layouts that are legal in HLSL.

As you point out, you also need a way to decorate HLSL shader resource references with Vulkan-style descriptor set/binding pairs.  The glslang and dxc/spiregg projects have worked together to define a syntax for those decorations, documented [here](https://github.com/KhronosGroup/glslang/wiki/HLSL-FAQ) for glslang. They have tried a couple of things, and I think I have heard that the attribute syntax, which looks like this:

[[vk::binding(3, 2)]]
StructuredBuffer<S> buffer3;

is preferred. Note that dxc would ignore the annotation when compiling for DX, so the same shader source works for both DX and Vulkan. 

OK, now that I've looked at it, the whole faq is seriously out of date. The HLSL entry should at least point to the projects. I'll create an internal issue. Thanks for the report.

**Comment by Khronoswebmaster** [comment]
FAQ has been removed as it was a bit too out of date.

**Comment by dneto0** [comment]
Tom included a link to the Glslang documentation about what dialect of HLSL is supported in Glslang

The "Spiregg" project is the addition of a SPIR-V for Vulkan backend to DXC.  Its documentation is at https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst
