### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Pixelec** [KhronosGroup/Khronosdotorg#82]
Hello, am I able to do something for that :

https://pastebin.com/f23uPdbh

notice that a diff points out that my code and vulkaninfo
produce exactly the same leak backtraces.

**Comment by karl-lunarg** [comment]
I think that this repo is more about the khronos.org website.  I'm not sure it is the best place to report technical problems.  That being said, this problem was already reported [here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1298).  There are also a large number of discussions out on the net about valgrind false positives with dlopen.  Perhaps the best way for you to do something about this is to create or find a valgrind supression file and use that so that you don't get the false positives while looking for other problems.

**Comment by Pixelec** [comment]
Yes!!! That was me, that was you. We already have this discussion. And I seen this bug disappear.
I posted [here](https://bugs.launchpad.net/ubuntu/+source/valgrind/+bug/1160352) a comment referencing this previous report. I didn't thought there were a new valgrind regression.
Sorry for this report. And thanks to you.
Can I just take the advantage of this bug report which is not... to ask you where could I find any irc channel or anything of the kind on vulkan, I've lots of questions on the spec. Thanks one again.

**Comment by karl-lunarg** [comment]
Questions about the Vulkan specification itself can probably be raised on [KhronosGroup/Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs).  I'm pretty sure that there's an IRC channel for Vulkan.  There is also mention of a Vulkan Slack channel on the [khronos.org website](https://www.khronos.org/news/archives).  It was dated Nov 27, so you may have to look at some older messages.
